apiVersion: v2
name: oracledb-exporter
description: A Helm chart to export queriy results from Oracle DB
type: application
version: "1.1.0"
appVersion: "0.6.0"
maintainers:
  - name: 'Milos Curuvija'
    email: 'curuvija@live.com'
annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/maintainers: |
    - name: "Milos Curuvija"
      email: curuvija@live.com
