apiVersion: v1
kind: Service
metadata:
  name: {{ include "starter.fullname" . }}
  labels:
    {{- include "starter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: listener
  selector:
    {{- include "starter.selectorLabels" . | nindent 4 }}
