preset: "extended"
commitMessageConventions:
  enabled:
    - conventionalCommits
services:
  github:
    type: "GITHUB"
    options:
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}" # replace this with gitlab token
      REPOSITORY_NAME: "charts"
      REPOSITORY_OWNER: "curuvija"
changelog:
  path: "build/CHANGELOG.md"
  template: "config/CHANGELOG.tpl"
  sections:
  "Added": "^feat$"
  "Fixed": "^fix$"
  substitutions:
    "(?m)#([0-9]+)(?s)": "[#%s](https://github.com/curuvija/charts/issues/%s)"
releaseTypes:
  remoteRepositories:
    - origin
  enabled:
    - mainline
    - develop
  publicationServices:
    - github
  items:
    mainline:
      description: "{{#fileContent}}CHANGELOG.md{{/fileContent}}"
      assets:
        - chart
      gitCommit: true
      #publishDraft: true
      filterTags: "^()?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)(-(main|master)(\\.([0-9]\\d*))?)$"
      gitPush: "true"
      gitTag: "true"
      #gitTagForce: "true"
      #gitPushForce: "true"
      matchBranches: "^(master|main)$" # publish only from master branch
      # matchEnvironmentVariables:
      #   CI: "^true$"                 # only match this release type when running on CI servers
      #matchWorkspaceStatus: "CLEAN"  # only match this release type when the repository is clean
      publish: "true"
# TODO: check if this is really needed
    develop:
      description: "{{#fileContent}}CHANGELOG.md{{/fileContent}}"
      assets:
        - chart
      collapseVersions: true
      collapsedVersionQualifier: "develop"
      releaseLenient: "true"
      filterTags: "^()?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)(-(develop|development)(\\.([0-9]\\d*))?)$"
      gitCommit: "false"
      gitPush: "true"
      gitTag: "true"
      gitTagForce: "true"
      gitPushForce: "true"
      gitTagNames:
        - ""
      #matchBranches: "^(develop|development|integration|latest)$"
      #matchWorkspaceStatus: "CLEAN"
      publish: "true"
      publishPreRelease: "true"
      versionRangeFromBranchName: false
git:
  remotes:
    origin:
      user: "curuvija"
      password: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}"

dryRun: false # use this together with verbosity and check logs in terminal
verbosity: "trace" # https://mooltiverse.github.io/nyx/guide/user/configuration-reference/global-options/#verbosity
# TODO: this one executes on all charts, figure out how to replace on the needed chart and check https://github.com/mooltiverse/nyx/issues/293
substitutions:
  enabled:
    #- helm_version # sets the version in Chart.yaml
    - chartyaml
  items:
    chartyaml:
      #files: "**/source/{{#environmentVariable}}HELM_CHART_NAME{{/environmentVariable}}/Chart.yaml"
      # TODO: it doesn't resolve environment variable
      files: "**/source/oracledb-exporter/Chart.yaml"
      match: "version:"
      replace: "version: 0.1.1"
stateFile: "build/.nyx-state.json"