preset: "extended"
# TODO: check how this work https://mooltiverse.github.io/nyx/guide/user/configuration-reference/commit-message-conventions/#commit-message-convention-definition
commitMessageConventions:
  enabled:
    - conventionalCommits
  # conventionalCommits:
  #   expression: (?m)^(?<type>[a-zA-Z0-9_]+)(\((?<scope>[a-z ]+)\))?(!)?:( (?<title>.+))$(?s).*
services:
  github:
    type: "GITHUB"
    options:
      AUTHENTICATION_TOKEN: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}" # replace this with gitlab token
      REPOSITORY_NAME: "charts"
      REPOSITORY_OWNER: "curuvija"
changelog:
  path: "build/CHANGELOG.md"
  template: "config/CHANGELOG.tpl"
  sections:
    "Added": ^feat$
    "Fixed": "^fix$"
  substitutions:
    "(?m)#([0-9]+)(?s)": "[#%s](https://github.com/curuvija/charts/issues/%s)"
releaseTypes:
  remoteRepositories:
    - origin
  enabled:
    - mainline
    - develop
  publicationServices:
    - github
  items:
    mainline:
      description: "{{#fileContent}}CHANGELOG.md{{/fileContent}}"
      assets:
        - chart
      gitCommit: true
      #publishDraft: true
      gitPush: "true"
      gitTag: "true"
      #gitTagForce: "true"
      #gitPushForce: "true"
      matchBranches: "^(master|main)$" # publish only from master branch
      # matchEnvironmentVariables:
      #   CI: "^true$"                 # only match this release type when running on CI servers
      #matchWorkspaceStatus: "CLEAN"  # only match this release type when the repository is clean
      publish: "true"
# TODO: check if this is really needed
    develop:
      description: "{{#fileContent}}CHANGELOG.md{{/fileContent}}"
      assets:
        - chart
      collapseVersions: true
      collapsedVersionQualifier: "develop"
      releaseLenient: "true"
      filterTags: "^()?([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)(-(develop|development)(\\.([0-9]\\d*))?)$"
      gitCommit: "false"
      gitPush: "true"
      gitTag: "true"
      gitTagForce: "true"
      gitPushForce: "true"
      matchBranches: "^(develop|development|integration|latest)$"
      #matchWorkspaceStatus: "CLEAN"
      publish: "true"
      publishPreRelease: "true"
      versionRangeFromBranchName: false
git:
  remotes:
    origin:
      user: "curuvija"
      password: "{{#environmentVariable}}GH_TOKEN{{/environmentVariable}}"

dryRun: false # use this together with verbosity and check logs in terminal
verbosity: "info" # https://mooltiverse.github.io/nyx/guide/user/configuration-reference/global-options/#verbosity
stateFile: "build/.nyx-state.json"