version: '3'

env:
  GITHUB_REPO: query-exporter

tasks:
  new:
    desc: creates new helm chart out of starter chart
    requires:
      vars:
        - NEW_HELM_CHART_NAME
    cmds:
      - helm create $NEW_HELM_CHART_NAME --starter $(pwd)/source/starter && mv $NEW_HELM_CHART_NAME source
  commitlint:
    desc: run commitlint
    cmds:
      - npx commitlint --from HEAD~1 --to HEAD --verbose
  lint:
    desc: run linters on Helm chart
    requires:
      vars: 
        - HELM_CHART_PATH
    cmds:
      - helm lint $HELM_CHART_PATH
      #- helm template $HELM_CHART_PATH | kubeval
  docs:
    desc: renders docs
    cmds:
      - helm-docs $CHART_PATH && cp $CHART_PATH/README.md .
  test:
    desc: test helm chart
    requires:
      vars: 
        - HELM_CHART_NAME
    cmds:
      - echo "Running tests for $HELM_CHART_NAME in folder tests/$HELM_CHART_NAME."
      - cd tests/$HELM_CHART_NAME && ls -la && go test ./...
  test_integration:
    desc: test helm chart with integrations tests
    cmds:
      - cd tests && go test --tags=integration
  package:
    desc: package helm chart with command like "HELM_CHART_PATH=source/query-exporter/query-exporter task package"
    requires:
      vars: 
        - HELM_CHART_PATH
    cmds:
      - helm package $HELM_CHART_PATH --destination build/
      # TODO: - cr package $CHART_PATH --sign
  upload:
    desc: upload packaged helm chart to github repository releases page
    cmds:
      - git checkout master
      - cr upload -o curuvija --git-repo $GITHUB_REPO --package-path .cr-release-packages/ --token $GH_TOKEN --release-notes-file CHANGELOG.md
      - cr upload -o curuvija --git-repo helm-charts --package-path .cr-release-packages/ --token $GH_TOKEN --release-notes-file CHANGELOG.md
  release:
    desc: release helm chart manually
    cmds:
      - task: lint
      - task: templates
      - task: docs
      - task: test
      - task: package
      - task: upload
  templates:
    desc: renders templates into folder
    cmds:
      - helm template default query-exporter/ > tests/rendered_templates/default.yaml
  infer:
    desc: nyx summary
    cmds:
      - nyx --summary infer
      - nyx infer --summary-file=build/nyx_summary
      #- docker run -it --rm -v .:/project mooltiverse/nyx:latest --summary infer
  mark:
    desc: mark nyx
    cmds:
      - nyx mark
  make:
    desc: make nyx
    cmds:
      - nyx make
      - task: appVersion
  publish:
    desc: publish nyx
    cmds:
      - nyx publish
  state:
    desc: build nyx state file
    cmds:
      - nyx --state-file=build/nyx-state.json infer
  appVersion:
    desc: replaces appVersion in Helm chart
    cmds:
      - export APP_VERSION=$(cat query-exporter/values.yaml | yq .image.tag) && yq e -i '.appVersion = env(APP_VERSION)' query-exporter/Chart.yaml
  golden:
    desc: update golden files
    requires:
      vars: 
        - HELM_CHART_NAME
    cmds:
      - |
        echo "working on chart $HELM_CHART_NAME"
        for file in tests/$HELM_CHART_NAME/values/*; do
          echo "working on file $($file)"
          helm template source/$HELM_CHART_NAME -n default --values $file > tests/$HELM_CHART_NAME/golden/$(basename $file)
        done
