version: '3'

env:
  GITHUB_REPO: charts
  CLUSTER_NAME: test-helm-chart-cluster
  SOURCE_DIR: source

tasks:
  prepare:
    desc: prepare environment for build stuff
    cmds:
      - echo "preparing stuff"
  new:
    desc: creates new helm chart out of starter chart
    requires:
      vars:
        - HELM_CHART_NAME
    cmds:
      - helm create $HELM_CHART_NAME --starter $(pwd)/$SOURCE_DIR/starter && mv $HELM_CHART_NAME $SOURCE_DIR
  commitlint:
    desc: run commitlint
    cmds:
      - npx commitlint --from HEAD~1 --to HEAD --verbose
  lint:
    desc: run linters on Helm chart
    requires:
      vars: 
        - HELM_CHART_NAME
    cmds:
      - helm lint $SOURCE_DIR/$HELM_CHART_NAME
      #- helm template $SOURCE_DIR/$HELM_CHART_NAME | kubeval
  docs:
    desc: renders docs
    requires:
      vars: 
        - HELM_CHART_NAME
    cmds:
      - helm-docs --chart-search-root $SOURCE_DIR/$HELM_CHART_NAME/
  tests:
    desc: test helm chart
    requires:
      vars: 
        - HELM_CHART_NAME # name of the helm chart
        - RELEASE_NAME # helm release name
    cmds:
      - echo "Running tests for $HELM_CHART_NAME in folder tests/$HELM_CHART_NAME."
      - cd tests/$HELM_CHART_NAME && ls -la && go test ./...
  tests.integration:
    desc: test helm chart with integrations tests
    # TODO: this doesn't work
    vars:
      HELM_CHART_PATH:
        sh: echo $(pwd)/$SOURCE_DIR/$HELM_CHART_NAME
    requires:
      vars: 
        - HELM_CHART_NAME # name of the helm chart
        - HELM_CHART_PATH # absolute path to the helm chart
        - RELEASE_NAME # helm release name
    cmds:
      - task: cluster.create
      - task: kubecontext
      - defer: { task: cluster.delete }
      - |
        export HELM_CHART_PATH=$(pwd)/$SOURCE_DIR/$HELM_CHART_NAME
        export RELEASE_NAME=$HELM_CHART_NAME
        echo "executing integration tests for helm chart $HELM_CHART_NAME in $HELM_CHART_PATH."
        cd tests/$HELM_CHART_NAME && go test --tags=integration
  package:
    desc: package helm chart with command like "HELM_CHART_PATH=$SOURCE_DIR/query-exporter/query-exporter task package"
    requires:
      vars: 
        - HELM_CHART_NAME
    cmds:
      - helm package $SOURCE_DIR/$HELM_CHART_NAME --destination build/ --destination .cr-release-packages/
      # TODO: - cr package $CHART_PATH --sign
  upload:
    desc: upload packaged helm chart to github repository releases page
    prompt: You are about to publish helm charts to charts repository... Do you want to continue?
    requires:
      vars:
        - GH_TOKEN
    cmds:
      - git checkout gh-pages
      - cr upload -o curuvija --git-repo $GITHUB_REPO --package-path .cr-release-packages/ --token $GH_TOKEN --release-notes-file $SOURCE_DIR/$HELM_CHART_NAME/CHANGELOG.md
      - cr upload -o curuvija --git-repo $GITHUB_REPO --package-path .cr-release-packages/ --token $GH_TOKEN --release-notes-file $SOURCE_DIR/$HELM_CHART_NAME/CHANGELOG.md
  release:
    desc: release helm chart
    cmds:
      - task: lint
      - task: golden
      - task: tests
      - task: docs
      - task: appVersion
      - task: package
      - task: version
      - task: diff
      - task: pr #--yes # check https://taskfile.dev/usage/#warning-prompts
      - task: commit
      - task: upload
      # TODO: check if you can have a webhook event created when PR is approved so that you can release the version to github pages https://stackoverflow.com/questions/56706424/github-api-does-a-webhook-fire-on-a-pull-request-approval-event
  infer:
    desc: nyx summary
    cmds:
      - nyx --summary infer
      - nyx infer --summary-file=build/nyx_summary
      #- docker run -it --rm -v .:/project mooltiverse/nyx:latest --summary infer
  mark:
    desc: mark nyx
    cmds:
      - nyx mark
  make:
    desc: make nyx
    cmds:
      - nyx make
      - task: appVersion
  publish:
    desc: publish nyx
    cmds:
      - nyx publish
  state:
    desc: build nyx state file
    cmds:
      - nyx --state-file=build/nyx-state.json infer
  version:
    desc: version helm chart
    cmds:
      - echo "versioning helm chart"
  diff:
    desc: display git diff
    cmds:
      - git --no-pager diff
  pr:
    desc: display changes imitating PR/MR
    prompt: By approving these changes you're going to publish release... Do you want to continue?
    cmds:
      - echo "creating release tag"
      - echo "commiting and creating PR"
  commit:
    desc: commit 
    cmds:
      - echo "creating release tag"
      - echo "commiting and creating PR (or even approve)"
  appVersion:
    desc: replaces appVersion in Helm chart
    requires:
      vars:
        - HELM_CHART_NAME
    cmds:
      - export APP_VERSION=$(cat $SOURCE_DIR/$HELM_CHART_NAME/values.yaml | yq .image.tag) && yq e -i '.appVersion = env(APP_VERSION)' $SOURCE_DIR/$HELM_CHART_NAME/Chart.yaml
  golden:
    desc: update golden files
    requires:
      vars: 
        - HELM_CHART_NAME
    cmds:
      - |
        echo "working on chart $HELM_CHART_NAME"
        for file in tests/$HELM_CHART_NAME/values/*; do
          echo "working on file $($file)"
          helm template $SOURCE_DIR/$HELM_CHART_NAME -n default --values $file > tests/$HELM_CHART_NAME/golden/$(basename $file)
        done
  cluster.create:
    desc: creates cluster for the lab
    requires:
      vars: 
        - CLUSTER_NAME
    cmds:
    - kind create cluster --config config/cluster.yaml --name $CLUSTER_NAME
  cluster.delete:
    desc: deletes the cluster for the lab
    requires:
      vars: 
        - CLUSTER_NAME
    cmds:
    - kind delete cluster --name $CLUSTER_NAME
  kubecontext:
    desc: select kubernetes kubecontext
    requires:
      vars: 
        - CLUSTER_NAME
    cmds:
    - kubectl config use-context kind-$CLUSTER_NAME
  up:
    desc: Install lab
    cmds:
    - task: cluster.create
    - task: kubecontext
    - task: helmfile
  down:
    desc: remove lab
    cmds:
    - task: cluster.delete
  helmfile:
    desc: helmfile
    cmds:
      - helmfile -f config/helmfile.yaml sync
  kube-score:
    desc: Run kube-score on templates
    cmds:
      - helm template $CHART_PATH | docker run -i zegl/kube-score:latest score -
  kube-linter:
    desc: run kube-linter
    cmds:
      - helm template $CHART_PATH | docker run -i stackrox/kube-linter:latest lint -
  polaris:
    desc: run polaris against helm chart, check https://github.com/FairwindsOps/polaris/blob/master/examples/config.yaml for config options
    cmds:
      - task: templates
      - docker run -t -v .:/path quay.io/fairwinds/polaris:latest polaris audit --only-show-failed-tests --format=pretty --audit-path /path/tests/rendered_templates
  trivy:
    desc: run trivy against helm chart
    cmds:
      - docker run -t -v .:/path aquasec/trivy:latest config /path/$CHART_PATH
  kubesec:
    desc: scan with https://kubesec.io/
    cmds:
      - helm template $CHART_PATH | docker run -i kubesec/kubesec:latest scan /dev/stdin
  kics:
    desc: run kics on helm chart
    cmds:
      - docker run -t -v .:/path checkmarx/kics:latest scan -p /path/$CHART_PATH
  # TODO: check https://github.com/bridgecrewio/checkov/blob/main/docs/7.Scan%20Examples/Helm.md
  checkov:
    desc: run checkouv on helm chart
    cmds:
      - docker run -t -v .:/path bridgecrew/checkov:latest -d /path/$CHART_PATH
  hooks:
    desc: runs all pre-commit hooks on demand
    cmds:
      - pre-commit run --all-files