---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-pipelines-cm
  labels:
{{ include "common.labels" . | nindent 4 }}
data:
  pipelines.yaml: |
  {{- toYaml .Values.pipelines | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-config-cm
  labels:
  {{ include "common.labels" . | nindent 4 }}
data:
  data-prepper-config.yaml: |
  {{- toYaml .Values.config | nindent 4 }}