apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}-server
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
{{- range $name, $service := .Values.ports }}
{{- if $service.enabled }}
    - port: {{ $service.port }}
      targetPort: {{ $service.port }}
      protocol: {{ $service.protocol }}
      name: {{ $name }}
{{- end }}
{{- end }}
  selector:
    {{- include "common.selectorLabels" . | nindent 4 }}
