services:
  oracle:
    # find details about image here https://github.com/wnameless/docker-oracle-xe-11g
    image: wnameless/oracle-xe-11g-r2:18.04-apex # or container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle
    ports:
      - "1521:1521"
    networks:
      - oracledb-exporter-lab
  oracledb-exporter:
    image: ghcr.io/iamseth/oracledb_exporter:0.6.0
    container_name: oracledb-exporter
    environment:
      DATA_SOURCE_NAME: "oracle://system:oracle@oracle:1521/xe"
    ports:
      - "9161:9161"
    networks:
      - oracledb-exporter-lab
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    networks:
      - oracledb-exporter-lab

networks:
  oracledb-exporter-lab:
    name: oracledb-exporter-lab

volumes:
  prom_data:
