apiVersion: v1
data:
  config.yaml: ZGF0YWJhc2VzOgogIGRiMToKICAgIGRzbjogc3FsaXRlOi8vCiAgICBjb25uZWN0LXNxbDoKICAgICAgLSBQUkFHTUEgYXBwbGljYXRpb25faWQgPSAxMjMKICAgICAgLSBQUkFHTUEgYXV0b192YWN1dW0gPSAxCiAgICBsYWJlbHM6CiAgICAgIHJlZ2lvbjogdXMxCiAgICAgIGFwcDogYXBwMQoKbWV0cmljczoKICBtZXRyaWMxOgogICAgdHlwZTogZ2F1Z2UKICAgIGRlc2NyaXB0aW9uOiBBIHNhbXBsZSBnYXVnZQoKcXVlcmllczoKICBxdWVyeTE6CiAgICBpbnRlcnZhbDogNQogICAgZGF0YWJhc2VzOiBbZGIxXQogICAgbWV0cmljczogW21ldHJpYzFdCiAgICBzcWw6IFNFTEVDVCByYW5kb20oKSAvIDEwMDAwMDAwMDAwMDAwMDAgQVMgbWV0cmljMQ==
kind: Secret
metadata:
  name: query-exporter-config-secret
  namespace: monitoring
