pipeline {
    agent { label 'k8s-helm-pod' }

    options{
        buildDiscarder(logRotator(numToKeepStr: '5', daysToKeepStr: '5'))
    }

    environment {
        GITHUB_TOKEN = credentials('github_curuvija_jcasc')
    }

    stages {
        stage('Lint') {
            steps {
                container('helm') {
                    sh 'helm lint data-prepper/'
                }
            }
        }
        stage('Scan for security issues') {
            steps {
                sh 'echo something'
            }
        }
        stage('Test') {
            steps {
                container('helm') {
                    sh 'cd tests && go test ./...'
                }
            }
        }
        stage('Template') {
            steps {
                container('helm') {
                    sh 'helm template data-prepper/'
                }
            }
        }
        stage('Dry run') {
            steps {
                sh 'echo something'
            }
        }
        stage('Generate docs') {
            steps {
                container('helm') {
                    sh 'helm-docs data-prepper/ && cp data-prepper/README.md .'
                }
            }
        }
        stage('Changelog') {
            steps {
                sh 'echo something'
            }
        }
        stage('Package Helm chart') {
            steps {
                container('helm') {
                    sh 'cr package data-prepper/'
                }
            }
        }
        stage('Upload Helm chart to releases') {
            when {
                allOf {
                    expression {
                        env.BRANCH_NAME == 'master'
                    }
                }
            }
            steps {
                container('helm') {
                    sh 'cr upload -o curuvija --git-repo data-prepper --package-path .cr-release-packages/ --token ${GITHUB_TOKEN_PSW}'
                }
            }
        }
        stage('Publish') {
            when {
                allOf {
                    expression {
                        env.BRANCH_NAME == 'master'
                    }
                }
            }
            steps {
                sh 'echo something'
            }
        }
        stage('Tag') {
            when {
                allOf {
                    expression {
                        env.BRANCH_NAME == 'master'
                    }
                }
            }
            steps {
                sh 'echo something'
            }
        }
    }
}
