releaseAssets:
  chart:
    description: "Data prepper Helm Chart version {{version}}"
    fileName: "data-prepper-{{version}}.tgz"
    path: "build/data-prepper-{{version}}.tgz"
    type: "application/octet-stream"
substitutions:
  enabled:
    - chartyaml
  items:
    chartyaml:
      files: "**/source/data-prepper/Chart.yaml"
      # match should work like the one bellow
      #match: "version: 1.0.0"
      match: "version: .*" # not the best one but it will work for now
      replace: 'version: "{{#capture expression="^[\D]*(?<semver>(?:\d+\.)?(?:\d+\.)?(?:\*|\d+))$" group="semver"}}{{version}}{{/capture}}"'
releaseTypes:
  items:
    mainline:
      gitTagNames:
        - "data-prepper-{{version}}"