version: '3'

env:
  CHART_NAME: data-prepper
  CHART_PATH: data-prepper
  GITHUB_REPO: data-prepper

tasks:
  deploy:
    desc: deploy helm chart to docker-desktop
    cmds:
      - kubectl config use-context docker-desktop
      - helm -n opensearch upgrade --install data-prepper data-prepper
  kube-score:
    desc: Run kube-score on templates
    cmds:
      - helm template $CHART_PATH | docker run -i zegl/kube-score:latest score -
  kube-linter:
    desc: run kube-linter
    cmds:
      - helm template $CHART_PATH | docker run -i stackrox/kube-linter:latest lint -
  polaris:
    desc: run polaris against helm chart, check https://github.com/FairwindsOps/polaris/blob/master/examples/config.yaml for config options
    cmds:
      - task: templates
      - docker run -t -v .:/path quay.io/fairwinds/polaris:latest polaris audit --only-show-failed-tests --format=pretty --audit-path /path/tests/rendered_templates
  trivy:
    desc: run trivy against helm chart
    cmds:
      - docker run -t -v .:/path aquasec/trivy:latest config /path/$CHART_PATH
  kubesec:
    desc: scan with https://kubesec.io/
    cmds:
      - helm template $CHART_PATH | docker run -i kubesec/kubesec:latest scan /dev/stdin
  kics:
    desc: run kics on helm chart
    cmds:
      - docker run -t -v .:/path checkmarx/kics:latest scan -p /path/$CHART_PATH
  # TODO: check https://github.com/bridgecrewio/checkov/blob/main/docs/7.Scan%20Examples/Helm.md
  checkov:
    desc: run checkouv on helm chart
    cmds:
      - docker run -t -v .:/path bridgecrew/checkov:latest -d /path/$CHART_PATH
  hooks:
    desc: runs all pre-commit hooks on demand
    cmds:
      - pre-commit run --all-files
  docs:
    desc: render docs
    cmds:
      - helm-docs $CHART_PATH && cp $CHART_PATH/README.md .
  tests:
    desc: test helm chart
    cmds:
      - cd tests && go test ./...
  tests.integration:
    desc: test helm chart with integrations tests
    cmds:
      - cd tests && go test --tags=integration
  package:
    desc: package helm chart
    cmds:
      - rm -rf .cr-release-packages/
      - git checkout master
      - cr package $CHART_PATH
  upload:
    desc: upload packaged helm chart to github repository releases page
    cmds:
      - git checkout master
      - cr upload -o curuvija --git-repo $GITHUB_REPO --package-path .cr-release-packages/ --token $GITHUB_TOKEN --release-notes-file CHANGELOG.md
      - cr upload -o curuvija --git-repo helm-charts --package-path .cr-release-packages/ --token $GITHUB_TOKEN --release-notes-file CHANGELOG.md
      - rm .cr-release-packages/*
  release:
    desc: release helm chart manually
    cmds:
      - task: lint
      - task: templates
      - task: docs
      - task: test
      - task: package
      - task: upload
  templates:
    desc: renders templates into folder
    cmds:
      - helm template default $CHART_PATH > tests/rendered_templates/default.yaml
  kind:
    desc: launch kind cluster (latest version)
    cmds:
      - kind create cluster --config tests/kind-cluster.yaml --name $CHART_PATH-test-cluster-latest --image kindest/node:latest
  kind-version:
    desc: launch kind cluster (specific version based on tags here https://hub.docker.com/r/kindest/node/tags)
    cmds:
      - kind create cluster --config tests/kind-cluster.yaml --name $CHART_PATH-test-cluster-version-specific --image kindest/node:{{.CLI_ARGS}}
