initialVersion: "2.1.0"
releaseAssets:
  chart:
    description: "Query Exporter Helm Chart Export Prometheus metrics from SQL queries"
    fileName: "query-exporter-{{version}}.tgz"
    path: "build/query-exporter-{{version}}.tgz"
    type: "application/octet-stream"
changelog:
  path: "source/query-exporter/chart/CHANGELOG.md"
substitutions:
  enabled:
    - chartyaml
  items:
    chartyaml:
      files: "**/source/query-exporter/chart/Chart.yaml"
      # match should work like the one bellow
      #match: "version: 1.0.0"
      match: "version: .*" # not the best one but it will work for now
      replace: 'version: "{{#capture expression="^[\D]*(?<semver>(?:\d+\.)?(?:\d+\.)?(?:\*|\d+))$" group="semver"}}{{version}}{{/capture}}"'
releaseTypes:
  items:
    mainline:
      filterTags: "^query-exporter-([0-9]\\d*)\\.([0-9]\\d*)\\.([0-9]\\d*)$"
      gitTagNames:
        - "query-exporter-{{version}}"