releaseAssets:
  chart:
    description: "Query Exporter Helm Chart version {{version}}"
    fileName: "query-exporter-{{version}}.tgz"
    path: "build/query-exporter-{{version}}.tgz"
    type: "application/octet-stream"
substitutions:
  enabled:
    - helm_version # sets the version in Chart.yaml